services:
  mysql:
    container_name: test-form-mysql
    image: mariadb:11.5.2
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - .docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=test_form
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user
    networks:
      - default

  php-fpm:
    container_name: test-form-php
    image: test-form-php-fpm
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/app
    depends_on:
      - mysql
    networks:
      - default

  nginx:
    container_name: test-form-nginx
    image: nginx:alpine
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./src/assets:/var/www/app/assets
    ports:
      - "180:80"
    depends_on:
      - php-fpm
    networks:
      - default

volumes:
  dbdata:

networks:
  default:
    name: test-php-fpm
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.169.210.0/26
